### ISSUE TITLE
Add support for primitives

### ISSUE THREAD

**Issue by dy** [slikts/tuplerone#5]
Primitives can be mapped to standard boxes via [primitive-pool](https://github.com/dy/primitive-pool) or similar technique.

Would make tuplerone truly great.

@slikts

**Comment by slikts** [comment]
Please see [`WeakishMap`](https://github.com/slikts/tuplerone/blob/master/src/WeakishMap.ts); the same can be done more simply by just using a `Map` for primitive keys. The issue why there still needs to be at least one non-primitive key is that it allows for the tuple (the mappings and the tuple object) to be collectible by GC if the non-primitive key stops being referenced anywhere. If there were only primitive keys, the tuple would never be collected, since it would always be reachable by the primitive keys.

**Comment by slikts** [comment]
Also, you've left out a type of primitives – symbols. 🙂

**Comment by slikts** [comment]
Fixed by adding `UnsafeTuple` in v3.
